name: Database Add

on:
  workflow_dispatch:

jobs:
  run-db-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install

      - name: Run DB Manager Script
        run: node scripts/db-manager.js load
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}